DROP TABLE `#__costbenefitprojection_diseasecategories`;
DROP TABLE `#__costbenefitprojection_diseases`;
DROP TABLE `#__costbenefitprojection_diseasedata`;
DROP TABLE `#__costbenefitprojection_interventions`;
DROP TABLE `#__costbenefitprojection_countries`;
DROP TABLE `#__costbenefitprojection_currencies`;
DROP TABLE `#__costbenefitprojection_helps`;
DROP TABLE `#__costbenefitprojection_defauldata`;
DROP TABLE `#__costbenefitprojection_memberdata`;